import { assets } from "./assets";
import type { Product } from "../types/product";

export const kurtisProducts: Product[] = [
  {
    id: "1",
    slug: "gulabi-tie-dye-kurti-set",
    name: "Gulabi Tie-dye Kurti Set",
    category: "LEHERIYA · KURTI SET",
    price: 2490,
    originalPrice: 3200,
    discountPercent: 22,
    rating: 4.5,
    reviewCount: 128,
    image: assets.products.gulabiTieDye,
    colors: [
      { hex: "#e4beb7" },
      { hex: "#b0cfa3" },
      { hex: "#ffffff" },
    ],
    badge: "SALE",
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "2",
    slug: "gulabi-leheriya-kurti-set",
    name: "Gulabi Leheriya Kurti Set",
    category: "LEHERIYA · KURTI SET",
    collection: "LEHERIYA COLLECTION",
    price: 3100,
    rating: 4.8,
    reviewCount: 94,
    image: assets.products.gulabiLeheriya,
    colors: [{ hex: "#e4beb7" }, { hex: "#d9c9a8" }],
    badge: "NEW",
    sizes: ["XS", "S", "M", "L", "XL"],
    description:
      "A hand-crafted leheriya kurti set featuring delicate tie-dye patterns in dusty rose, paired with matching palazzo pants. Made from breathable cotton lawn for all-day comfort.",
  },
  {
    id: "3",
    slug: "midnight-kari-grace-set",
    name: "Midnight Kari Grace Set",
    category: "EMBROIDERED · KURTI SET",
    price: 5400,
    rating: 5,
    reviewCount: 67,
    image: assets.products.product2,
    colors: [{ hex: "#141210" }, { hex: "#36512e" }],
    badge: "BESTSELLER",
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "4",
    slug: "threads-of-paradise-kurti",
    name: "Threads of Paradise Kurti",
    category: "FLORAL · STRAIGHT KURTI",
    price: 1890,
    originalPrice: 2400,
    discountPercent: 21,
    rating: 4.2,
    reviewCount: 45,
    image: assets.products.product3,
    colors: [{ hex: "#b0cfa3" }, { hex: "#d9c9a8" }],
    sizes: ["XS", "S", "M", "L"],
  },
  {
    id: "5",
    slug: "whispers-of-charm-set",
    name: "Whispers of Charm Set",
    category: "A-LINE · KURTI SET",
    price: 4200,
    rating: 4.6,
    reviewCount: 83,
    image: assets.products.gulabiTieDye,
    colors: [{ hex: "#e4beb7" }],
    badge: "NEW",
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "6",
    slug: "terracotta-anarkali",
    name: "Terracotta Heritage Anarkali",
    category: "ANARKALI · SUIT SET",
    price: 6800,
    rating: 4.9,
    reviewCount: 112,
    image: assets.products.gulabiLeheriya,
    colors: [{ hex: "#c4704a" }, { hex: "#d9c9a8" }],
    sizes: ["S", "M", "L"],
  },
];

export const jewelleryProducts: Product[] = [
  {
    id: "j1",
    slug: "chandrika-silver-choker",
    name: "Chandrika Silver Choker",
    category: "NECKLACE · GERMAN SILVER",
    price: 4500,
    rating: 4.7,
    reviewCount: 56,
    image: assets.products.jodhaNecklace,
    colors: [{ hex: "#c0c0c0" }],
    badge: "BESTSELLER",
  },
  {
    id: "j2",
    slug: "midnight-kari-earrings",
    name: "Midnight Kari Drop Earrings",
    category: "EARRINGS · ANTI-TARNISH",
    price: 1450,
    rating: 4.5,
    reviewCount: 34,
    image: assets.products.silverEarrings,
    colors: [{ hex: "#c0c0c0" }],
    badge: "NEW",
  },
  {
    id: "j3",
    slug: "rajwada-silver-kada-set",
    name: "Rajwada Silver Kada Set",
    category: "BANGLES · OXIDISED",
    price: 6200,
    rating: 4.3,
    reviewCount: 28,
    image: assets.products.silverBangles,
    colors: [{ hex: "#8b7355" }],
  },
  {
    id: "j4",
    slug: "aanya-pendant",
    name: "Aanya Pendant",
    category: "PENDANT · GERMAN SILVER",
    price: 2100,
    rating: 4.6,
    reviewCount: 41,
    image: assets.products.silverPendant,
    colors: [{ hex: "#c0c0c0" }],
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return [...kurtisProducts, ...jewelleryProducts].find((p) => p.slug === slug);
}

export const homeNewArrivals = kurtisProducts.slice(0, 4);
